import Head from 'next/head'
import Image from 'next/image'
import HeroImage from '../components/HeroImage'
import styles from '../styles/Home.module.css'
import heroImagePhoto from '../public/HeroImage/lss-hero-medium.jpg'
import heroImageMobile from '../public/HeroImage/lss-hero-mobile.jpg'

export default function Home() {
  return (
	<div className={styles.container}>
		<Head>
			<title>Leblanc Software Solutions</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>

		<HeroImage image={heroImagePhoto}/>


		<section className={styles.main}>
			<div className={styles.aboutWrapper}>
			   <div className={styles.titleContainer}>
					<h1>We build <span>beautiful</span>, <span>performant</span> websites that <span>scale</span>.<br></br> Using Frameworks like Nextj. We are able to provide the versatility of choosing the best and fastest way to render your website. </h1>   
				</div>

                <div className={styles.imageWrapper}>
                    <div className={styles.imageContainer}>
                        <h1>Turning this</h1>
                        <Image 
                            src="/pagespeed-insights-mobile-1.png" alt="about us" width={1024} height={800}
                            className={styles.introimage} 
                        /> <br></br>
                        <h1>Into this </h1>
                        <Image 
                            src="/pagespeed-insights-mobile-2.png" alt="about us" width={1024} height={800} 
                            className={styles.introimage}
                        />
                    </div>
                </div> 

			    <div className={styles.titleContainer}>
					<h1>As a young company, we have decided to specialize in Web and App design & development services first before expanding to offer additional services such as SAAS products etc</h1>   
				</div> 
			</div>

            {/* Services Section  */}
			<div className={styles.servicesWrapper}>
				<div className={styles.servicesContainer}>
					<h1 className={styles.serviceh1}>Services</h1>
					<div className={styles.services}>
                        <div className={styles.service}>
                            <h2>Web Development & Design</h2>
                            <Image 
                                src="/pagespeed-insights-mobile-1.png"
                                width={1024}
                                height={800}
                            />
                            <p>We build beautiful, performant websites that scale. Using Frameworks like Nextj. We are able to provide the versatility of choosing the best and fastest way to render your website.</p>
                        </div>

                         <div className={styles.service}>
                            <h2>App Development & Design</h2>
                            <Image 
                                src="/pagespeed-insights-mobile-1.png"
                                width={1024}
                                height={800}
                            />
                            <p>We build beautiful, performant websites that scale. Using Frameworks like Nextj. We are able to provide the versatility of choosing the best and fastest way to render your website.</p>
                        </div>

                         <div className={styles.service}>
                            <h2>UI | UX Design</h2>
                            <Image 
                                src="/pagespeed-insights-mobile-1.png"
                                width={1024}
                                height={800}
                            />
                            <p>We build beautiful, performant websites that scale. Using Frameworks like Nextj. We are able to provide the versatility of choosing the best and fastest way to render your website.</p>
                        </div>

                          <div className={styles.service}>
                            <h2>IT Consulting</h2>
                            <Image 
                                src="/pagespeed-insights-mobile-1.png"
                                width={1024}
                                height={800}
                            />
                            <p>We build beautiful, performant websites that scale. Using Frameworks like Nextj. We are able to provide the versatility of choosing the best and fastest way to render your website.</p>
                        </div>
					</div>
				</div>
		
			</div>




		</section>

	</div>
  )
}
