import Head from 'next/head'
import Image from 'next/image'
import HeroImage from '../components/HeroImage'
import styles from '../styles/Home.module.css'

// services images
import webdev from '../public/services/web-dev.jpg'
import appdevlarge from '../public/services/app-dev-large.jpg'
import consulting from '../public/services/consulting.jpg'
import mobilehero from '../public/HeroImage/lss-hero-mobile.jpg'
import ui from '../public/services/ui-dev-small.jpg'

import pagespeed1 from '../public/pagespeed-insights-mobile-1.png'
import pagespeed2 from '../public/pagespeed-insights-mobile-2.png'

export default function Home() {
  return (
	<div className={styles.container}>
		<Head>
			<title>Leblanc Software Solutions</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/public/favicon.ico" />

            <!-- Global site tag (gtag.js) - Google Analytics -->
            <script async src="https://www.googletagmanager.com/gtag/js?id=G-PCEC1Z0BMQ">
                
            </script>
            <script>
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());

                gtag('config', 'G-PCEC1Z0BMQ');
            </script>
		</Head>

		<div className={styles.heroImage}>
			<HeroImage />

		</div>

		<div className={styles.mobileHero}>
			<Image 
				src={mobilehero} alt="about us" width={1920} height={3600} className={styles.mobileHeroImage}
			/>
		</div>

		<section className={styles.main}>
			<div className={styles.aboutWrapper}>
			   <div className={styles.titleContainer}>
					<h1>We build <span>beautiful</span>, <span>performant</span> websites that <span>scale</span>.<br></br> Using Frameworks like Nextj. We are able to provide the versatility of choosing the best and fastest way to render your website. </h1>   
				</div>

                <div className={styles.imageWrapper}>
                    <div className={styles.imageContainer}><h1>Turning this</h1>
                        <Image src={pagespeed1} alt="about us" width={1024} height={800} />
                        <Image src={pagespeed2} alt="about us" width={1024} height={800} /><h1>Into this</h1>
                    </div>
                </div> 

			    <div className={styles.titleContainer}>
					<h1>As a young company, we have decided to specialize in Web and App design & development services first before expanding to offer additional services such as SAAS products etc</h1>   
				</div> 
			</div>


				 {/* Services Section  */}
				 <div className={styles.servicesWrapper}>
				<div className={styles.servicesContainer}>
					<h1>Services</h1>
					<div className={styles.services}>
                        <div className={styles.service}>
                            <h2>Web Dev and Design</h2>
                            <Image 
                                src={webdev} alt="about us" width={1024} height={800}
                               
                            />
                            <p>We build beautiful, performant websites that scale. Using Frameworks like Nextj. We are able to provide the versatility of choosing the best and fastest way to render your website.</p>
                        </div>

                         <div className={styles.service}>
                            <h2>App Dev and Design</h2>
                            <Image 
                                src={appdevlarge} alt="about us" width={1024} height={800}
                                
                            />
                            <p>We use React Native to build blazing fast cross-platform mobile applications. One codebase for all platforms. That means easier maintaining, adding features faster, and overall just easier.</p>
                        </div>

                         <div className={styles.service}>
                            <h2>UI and UX Design</h2>
                            <Image 
                                src={ui} alt="about us" width={1024} height={800}
                              
                            />
                            <p>We build user interfaces and user experiences. UI UX can be a complicated beast, and one that can be difficult to get right. Let us worry about the interface, and you worry about making the best product.</p>
                        </div>

                          <div className={styles.service}>
                            <h2>IT Consulting</h2>
                            <Image 
                                src={consulting} alt="about us" width={1024} height={800}
                              
                            />
                            <p>We offer IT Consulting for when you have an idea but do not know where to begin with the tech to implement it. We can sit down and discuss your needs and offer options for you to choose from. The first hour of consultation is free.</p>
                        </div>
					</div>
				</div>
		
			</div>
		




		</section>

	</div>
  )
}
